### ISSUE TITLE
GPS Log export hangup when points size = 0

### ISSUE THREAD

**Issue by sanak** [gtt-project/smash_import_export_plugins#6]
**Problem**
GPS Log export hangup when points size = 0.
```
E/flutter (32349): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Bad state: No element
E/flutter (32349): #0      List.first (dart:core-patch/growable_array.dart:360:5)
E/flutter (32349): #1      GttUtilities.createLogIssue (package:smash_import_export_plugins/com/hydrologis/smash/import_export_plugins/utils/gtt_utilities.dart:272:29)
E/flutter (32349): #2      _GttExportWidgetState.uploadProjectData (package:smash_import_export_plugins/com/hydrologis/smash/import_export_plugins/export/gtt/gtt_export.dart:792:24)
E/flutter (32349): #3      _GttExportWidgetState.build.<anonymous closure> (package:smash_import_export_plugins/com/hydrologis/smash/import_export_plugins/export/gtt/gtt_export.dart:568:19)
E/flutter (32349): <asynchronous suspension>
E/flutter (32349): 
```

**To Reproduce**
1. Turn on GPS logging in house
2. Turn off it without moving
3. Export GPS log with selecting a project

**Expectation**
points size = 0 GPS log should be skipped without hangup.

**Screenshots**
<img src="https://user-images.githubusercontent.com/629923/174740394-bd87dffc-be81-4942-b244-12145fadce10.jpg" width="300px">

**Platform/smartphone:**
 - Device: ASUS ZenFone (X00RD)
 - OS: Android 8.0
 - App Version: develop branch (commit: https://github.com/gtt-project/smash_import_export_plugins/commit/f9074818b49d374853704ef417f24e85dedcd5c6)

**Comment by sanak** [comment]
Okay, I confirmed the issue is fixed on the latest `develop` branch. Thanks!
